{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "d489d256-6323-43ff-9670-d25e63f0c573",
   "metadata": {
    "tags": []
   },
   "outputs": [],
   "source": [
    "#!pip install yfinance --upgrade --force-reinstall"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "9e054fb0-6071-4fc0-8d29-153087feda25",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Fetching data for: AAPL\n",
      "Fetching data for: MSFT\n",
      "Fetching data for: AMZN\n",
      "Fetching data for: NVDA\n",
      "Fetching data for: GOOGL\n",
      "Fetching data for: GOOG\n",
      "Fetching data for: META\n",
      "Fetching data for: TSLA\n",
      "Fetching data for: BRK-B\n",
      "Fetching data for: UNH\n",
      "Fetching data for: JPM\n",
      "Fetching data for: JNJ\n",
      "Fetching data for: XOM\n",
      "Fetching data for: V\n",
      "Fetching data for: PG\n",
      "Fetching data for: MA\n",
      "Fetching data for: LLY\n",
      "Fetching data for: HD\n",
      "Fetching data for: AVGO\n",
      "Fetching data for: CVX\n",
      "Fetching data for: ABBV\n",
      "Fetching data for: COST\n",
      "Fetching data for: MRK\n",
      "Fetching data for: PEP\n",
      "Fetching data for: KO\n",
      "Fetching data for: MCD\n",
      "Fetching data for: ADBE\n",
      "Fetching data for: TMO\n",
      "Fetching data for: NFLX\n",
      "Fetching data for: CRM\n",
      "Fetching data for: AMD\n",
      "Fetching data for: PFE\n",
      "Fetching data for: ABT\n",
      "Fetching data for: INTC\n",
      "Fetching data for: CMCSA\n",
      "Fetching data for: ACN\n",
      "Fetching data for: LIN\n",
      "Fetching data for: VZ\n",
      "Fetching data for: ORCL\n",
      "Fetching data for: WFC\n",
      "Fetching data for: DIS\n",
      "Fetching data for: TXN\n",
      "Fetching data for: NKE\n",
      "Fetching data for: QCOM\n",
      "Fetching data for: DHR\n",
      "Fetching data for: PM\n",
      "Fetching data for: RTX\n",
      "Fetching data for: IBM\n",
      "Fetching data for: UNP\n",
      "Fetching data for: CAT\n",
      "Fetching data for: LOW\n",
      "Fetching data for: GS\n",
      "Fetching data for: HON\n",
      "Fetching data for: SPGI\n",
      "Fetching data for: NOW\n",
      "Fetching data for: MS\n",
      "Fetching data for: BLK\n",
      "Fetching data for: SCHW\n",
      "Fetching data for: LMT\n",
      "Fetching data for: BA\n",
      "Fetching data for: MDT\n",
      "Fetching data for: ELV\n",
      "Fetching data for: BKNG\n",
      "Fetching data for: T\n",
      "Fetching data for: ISRG\n",
      "Fetching data for: GILD\n",
      "Fetching data for: GE\n",
      "Fetching data for: AMAT\n",
      "Fetching data for: DE\n",
      "Fetching data for: C\n",
      "Fetching data for: PLD\n",
      "Fetching data for: DUK\n",
      "Fetching data for: BSX\n",
      "Fetching data for: PYPL\n",
      "Fetching data for: SBUX\n",
      "Fetching data for: AXP\n",
      "Fetching data for: TGT\n",
      "Fetching data for: MO\n",
      "Fetching data for: CB\n",
      "Fetching data for: ADP\n",
      "Fetching data for: SO\n",
      "Fetching data for: CI\n",
      "Fetching data for: AMGN\n",
      "Fetching data for: EQIX\n",
      "Fetching data for: BDX\n",
      "Fetching data for: USB\n",
      "Fetching data for: REGN\n",
      "Fetching data for: MMC\n",
      "Fetching data for: ADI\n",
      "Fetching data for: MU\n",
      "Fetching data for: PGR\n",
      "Fetching data for: VRTX\n",
      "Fetching data for: MDLZ\n",
      "Fetching data for: ZTS\n",
      "Fetching data for: PNC\n",
      "Fetching data for: CME\n",
      "Fetching data for: CSX\n",
      "Fetching data for: TFC\n",
      "Fetching data for: EOG\n",
      "Fetching data for: ICE\n",
      "Data saved to financial_data.csv\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/var/folders/wj/50s22k6s5fq9mdbzjvgv5zc00000gn/T/ipykernel_25453/552118445.py:72: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.\n",
      "  df = pd.concat([df, pd.DataFrame(data_list)], ignore_index=True)\n"
     ]
    }
   ],
   "source": [
    "import yfinance as yf\n",
    "import pandas as pd\n",
    "import time\n",
    "\n",
    "# List of stock tickers (Example)\n",
    "tickers = [\"AAPL\", \"MSFT\", \"NVDA\", \"GOOGL\", \"AMZN\"]\n",
    "sp100 = [\n",
    "    \"AAPL\", \"MSFT\", \"AMZN\", \"NVDA\", \"GOOGL\", \"GOOG\", \"META\", \"TSLA\", \"BRK-B\", \"UNH\",\n",
    "    \"JPM\", \"JNJ\", \"XOM\", \"V\", \"PG\", \"MA\", \"LLY\", \"HD\", \"AVGO\", \"CVX\",\n",
    "    \"ABBV\", \"COST\", \"MRK\", \"PEP\", \"KO\", \"MCD\", \"ADBE\", \"TMO\", \"NFLX\", \"CRM\",\n",
    "    \"AMD\", \"PFE\", \"ABT\", \"INTC\", \"CMCSA\", \"ACN\", \"LIN\", \"VZ\", \"ORCL\", \"WFC\",\n",
    "    \"DIS\", \"TXN\", \"NKE\", \"QCOM\", \"DHR\", \"PM\", \"RTX\", \"IBM\", \"UNP\", \"CAT\",\n",
    "    \"LOW\", \"GS\", \"HON\", \"SPGI\", \"NOW\", \"MS\", \"BLK\", \"SCHW\", \"LMT\", \"BA\",\n",
    "    \"MDT\", \"ELV\", \"BKNG\", \"T\", \"ISRG\", \"GILD\", \"GE\", \"AMAT\", \"DE\", \"C\",\n",
    "    \"PLD\", \"DUK\", \"BSX\", \"PYPL\", \"SBUX\", \"AXP\", \"TGT\", \"MO\", \"CB\", \"ADP\",\n",
    "    \"SO\", \"CI\", \"AMGN\", \"EQIX\", \"BDX\", \"USB\", \"REGN\", \"MMC\", \"ADI\", \"MU\",\n",
    "    \"PGR\", \"VRTX\", \"MDLZ\", \"ZTS\", \"PNC\", \"CME\", \"CSX\", \"TFC\", \"EOG\", \"ICE\"\n",
    "]\n",
    "\n",
    "etfs = [\"EWJ\",\"EWG\",\"EWU\",\"INDA\",\"IEV\",\"MCHI\",\"XLE\",\"REZ\",\"IFY\",\"IYW\",\"IYC\",\"IYH\",\"IYZ\",\"IYJ\",\"IYK\"]\n",
    "\n",
    "tickers = sp100\n",
    "\n",
    "# Create an empty DataFrame\n",
    "df = pd.DataFrame(columns=[\"Ticker\", \"Company Name\", \"PE Ratio TTM\", \"PE Forward\", \"ROE\", \"ROA\", \"Dividend Paid\"])\n",
    "\n",
    "# Temporary list to store data\n",
    "data_list = []\n",
    "\n",
    "# Fetch financial data for each ticker\n",
    "for ticker in tickers:\n",
    "    try:\n",
    "        stock = yf.Ticker(ticker)\n",
    "        print(f\"Fetching data for: {ticker}\")\n",
    "        time.sleep(0.10)  # Sleep to avoid rate limits\n",
    "\n",
    "        # Extract relevant data, handling missing values\n",
    "        hist = stock.history(period=\"1d\")\n",
    "        info = stock.info\n",
    "        pe_ratio_ttm = info.get(\"trailingPE\", None)\n",
    "        pe_forward = info.get(\"forwardPE\", None)\n",
    "        roe = info.get(\"returnOnEquity\", None)\n",
    "        roa = info.get(\"returnOnAssets\", None)\n",
    "        dividend_paid = info.get(\"dividendRate\", None)\n",
    "        company_name = info.get(\"shortName\", ticker)  # Use ticker if name is unavailable\n",
    "        beta = info.get(\"beta\", None)  # Stock beta\n",
    "        closing_price = hist[\"Close\"].iloc[-1] if not hist.empty else None  # Most recent closing price\n",
    "        one_year_target = info.get(\"targetMeanPrice\", None)\n",
    "\n",
    "\n",
    "        # Append data to list\n",
    "        data_list.append({\n",
    "            \"Ticker\": ticker,\n",
    "            \"Company Name\": company_name,\n",
    "            \"Price\": closing_price,\n",
    "            \"Beta\": beta,\n",
    "            \"PE Ratio TTM\": pe_ratio_ttm,\n",
    "            \"PE Forward\": pe_forward,\n",
    "            \"ROE\": roe,\n",
    "            \"ROA\": roa,\n",
    "            \"Dividend Paid\": dividend_paid,\n",
    "            \"YTarget\":one_year_target\n",
    "        })\n",
    "\n",
    "    except Exception as e:\n",
    "        print(f\"Error fetching data for {ticker}: {e}\")\n",
    "        time.sleep(5)  # Wait if error occurs\n",
    "\n",
    "\n",
    "        \n",
    "# Convert list to DataFrame using pd.concat()\n",
    "df = pd.concat([df, pd.DataFrame(data_list)], ignore_index=True)\n",
    "\n",
    "# Save to CSV\n",
    "df.to_csv(\"financial_data.csv\", index=False)\n",
    "print(\"Data saved to financial_data.csv\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "75e16773-09d6-45f3-b6a5-516e72715e5b",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data saved to financial_data.csv\n"
     ]
    }
   ],
   "source": [
    "df[\"PE_Rank\"] = df[\"PE Ratio TTM\"].rank(method=\"min\") \n",
    "# df[\"PE_Score\"] = ((df[\"PE Ratio TTM\"].max() - df[\"PE Ratio TTM\"]) / (df[\"PE Ratio TTM\"].max() - df[\"PE Ratio TTM\"].min())) * 4 + 1\n",
    "df[\"PE_Score\"] = 4* ((df[\"PE_Rank\"].max() - df[\"PE_Rank\"]) / (df[\"PE_Rank\"].max() - df[\"PE_Rank\"].min())) + 1\n",
    "\n",
    "# Scale PE Forward (Lower is Better, so Inverted)\n",
    "df[\"PE_Forward_Score\"] = 5 - (4*(( df[\"PE Forward\"]-df[\"PE Forward\"].min()) / \n",
    "                          (df[\"PE Forward\"].max() - df[\"PE Forward\"].min())))\n",
    "\n",
    "# Scale ROE (Higher is Better)\n",
    "df[\"ROER\"] = df[\"ROE\"].rank(method=\"max\") \n",
    "df[\"ROE_Score\"] = ((df[\"ROER\"] - df[\"ROER\"].min()) / \n",
    "                   (df[\"ROER\"].max() - df[\"ROER\"].min())) * 4 + 1\n",
    "\n",
    "# Scale ROA (Higher is Better)\n",
    "df[\"ROAR\"] = df[\"ROA\"].rank(method=\"max\") \n",
    "df[\"ROA_Score\"] = ((df[\"ROAR\"] - df[\"ROAR\"].min()) / \n",
    "                   (df[\"ROAR\"].max() - df[\"ROAR\"].min())) * 4 + 1\n",
    "\n",
    "# Scale Dividend Paid (Higher is Better)\n",
    "df[\"DivR\"] = df[\"Dividend Paid\"].rank(method=\"max\") \n",
    "df[\"Dividend_Score\"] = ((df[\"DivR\"] - df[\"DivR\"].min()) / \n",
    "                        (df[\"DivR\"].max() - df[\"DivR\"].min())) * 4 + 1\n",
    "\n",
    "#df[\"PE_Score\"] = df.apply(lambda x: 1.0 if x[\"PE_Score\"] < df[\"PE_Score\"].median() else x[\"PE_Score\"], axis=1)\n",
    "\n",
    "df[\"Score\"] = (0.35 * df[\"PE_Score\"] + \n",
    "               0.35 * df[\"ROE_Score\"] + \n",
    "               0.15 * df[\"ROA_Score\"] + \n",
    "               0.15 * df[\"Dividend_Score\"])\n",
    "\n",
    "threshold = df[\"PE Ratio TTM\"].quantile(0.6)  # Find the 60th percentile (top 40% starts above this)\n",
    "df[\"Score\"] = df.apply(lambda x: 0 if x[\"PE Ratio TTM\"] > threshold else x[\"Score\"], axis=1)\n",
    "\n",
    "\n",
    "ordered_columns = [\"Ticker\", \"Company Name\", \"Price\", \"YTarget\", \"Beta\", \"Score\", \"PE_Score\",\"PE Ratio TTM\", \"PE Forward\", \"ROE_Score\", \"ROE\", \"ROA_Score\",\"ROA\", \"Dividend_Score\", \"Dividend Paid\"]\n",
    "# Reorder DataFrame\n",
    "df = df[ordered_columns]\n",
    "\n",
    "df = df.sort_values(by=\"Score\", ascending=False)\n",
    "# Save to CSV\n",
    "df.to_csv(\"financial_data_35_35_15_15_all_final.csv\", index=False)\n",
    "print(\"Data saved to financial_data.csv\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "9da47727-e463-4cdf-97c2-2d1a24085bde",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Data saved to financial_data.csv\n"
     ]
    }
   ],
   "source": [
    "df = df.sort_values(by=\"Score\", ascending=False)\n",
    "# Save to CSV\n",
    "df.to_csv(\"financial_data_25_all_final.csv\", index=False)\n",
    "print(\"Data saved to financial_data.csv\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "8925c043-56a0-4f55-b09a-c2d16ddf5c27",
   "metadata": {
    "tags": []
   },
   "outputs": [
    {
     "data": {
      "text/html": [
       "<div>\n",
       "<style scoped>\n",
       "    .dataframe tbody tr th:only-of-type {\n",
       "        vertical-align: middle;\n",
       "    }\n",
       "\n",
       "    .dataframe tbody tr th {\n",
       "        vertical-align: top;\n",
       "    }\n",
       "\n",
       "    .dataframe thead th {\n",
       "        text-align: right;\n",
       "    }\n",
       "</style>\n",
       "<table border=\"1\" class=\"dataframe\">\n",
       "  <thead>\n",
       "    <tr style=\"text-align: right;\">\n",
       "      <th></th>\n",
       "      <th>Ticker</th>\n",
       "      <th>Company Name</th>\n",
       "      <th>Price</th>\n",
       "      <th>YTarget</th>\n",
       "      <th>Beta</th>\n",
       "      <th>Score</th>\n",
       "      <th>PE_Score</th>\n",
       "      <th>PE Ratio TTM</th>\n",
       "      <th>PE Forward</th>\n",
       "      <th>ROE_Score</th>\n",
       "      <th>ROE</th>\n",
       "      <th>ROA_Score</th>\n",
       "      <th>ROA</th>\n",
       "      <th>Dividend_Score</th>\n",
       "      <th>Dividend Paid</th>\n",
       "    </tr>\n",
       "  </thead>\n",
       "  <tbody>\n",
       "    <tr>\n",
       "      <th>49</th>\n",
       "      <td>CAT</td>\n",
       "      <td>Caterpillar, Inc.</td>\n",
       "      <td>339.640015</td>\n",
       "      <td>391.12564</td>\n",
       "      <td>1.138</td>\n",
       "      <td>4.291451</td>\n",
       "      <td>4.326316</td>\n",
       "      <td>15.410163</td>\n",
       "      <td>15.333635</td>\n",
       "      <td>4.565217</td>\n",
       "      <td>0.55327</td>\n",
       "      <td>3.828283</td>\n",
       "      <td>0.09675</td>\n",
       "      <td>4.034483</td>\n",
       "      <td>5.64</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>17</th>\n",
       "      <td>HD</td>\n",
       "      <td>Home Depot, Inc. (The)</td>\n",
       "      <td>351.309998</td>\n",
       "      <td>431.95514</td>\n",
       "      <td>1.090</td>\n",
       "      <td>4.286908</td>\n",
       "      <td>3.273684</td>\n",
       "      <td>23.577852</td>\n",
       "      <td>22.519870</td>\n",
       "      <td>5.000000</td>\n",
       "      <td>3.85372</td>\n",
       "      <td>4.595960</td>\n",
       "      <td>0.15585</td>\n",
       "      <td>4.678161</td>\n",
       "      <td>9.20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>58</th>\n",
       "      <td>LMT</td>\n",
       "      <td>Lockheed Martin Corporation</td>\n",
       "      <td>466.170013</td>\n",
       "      <td>544.62410</td>\n",
       "      <td>0.427</td>\n",
       "      <td>4.174352</td>\n",
       "      <td>3.610526</td>\n",
       "      <td>20.876400</td>\n",
       "      <td>16.583778</td>\n",
       "      <td>4.695652</td>\n",
       "      <td>0.81045</td>\n",
       "      <td>3.585859</td>\n",
       "      <td>0.08306</td>\n",
       "      <td>4.862069</td>\n",
       "      <td>13.20</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>22</th>\n",
       "      <td>MRK</td>\n",
       "      <td>Merck &amp; Company, Inc.</td>\n",
       "      <td>94.570000</td>\n",
       "      <td>112.28545</td>\n",
       "      <td>0.363</td>\n",
       "      <td>4.114825</td>\n",
       "      <td>4.452632</td>\n",
       "      <td>14.031158</td>\n",
       "      <td>10.060638</td>\n",
       "      <td>4.260870</td>\n",
       "      <td>0.40789</td>\n",
       "      <td>4.353535</td>\n",
       "      <td>0.13903</td>\n",
       "      <td>2.747126</td>\n",
       "      <td>3.24</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>43</th>\n",
       "      <td>QCOM</td>\n",
       "      <td>QUALCOMM Incorporated</td>\n",
       "      <td>156.580002</td>\n",
       "      <td>198.49700</td>\n",
       "      <td>1.289</td>\n",
       "      <td>4.009431</td>\n",
       "      <td>4.115789</td>\n",
       "      <td>16.891047</td>\n",
       "      <td>12.802944</td>\n",
       "      <td>4.304348</td>\n",
       "      <td>0.41968</td>\n",
       "      <td>4.151515</td>\n",
       "      <td>0.12626</td>\n",
       "      <td>2.931034</td>\n",
       "      <td>3.40</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>...</th>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "      <td>...</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>62</th>\n",
       "      <td>BKNG</td>\n",
       "      <td>Booking Holdings Inc. Common St</td>\n",
       "      <td>4465.479980</td>\n",
       "      <td>5636.97600</td>\n",
       "      <td>1.404</td>\n",
       "      <td>NaN</td>\n",
       "      <td>3.021053</td>\n",
       "      <td>25.840403</td>\n",
       "      <td>21.279388</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4.838384</td>\n",
       "      <td>0.18225</td>\n",
       "      <td>5.000000</td>\n",
       "      <td>38.40</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>73</th>\n",
       "      <td>PYPL</td>\n",
       "      <td>PayPal Holdings, Inc.</td>\n",
       "      <td>68.949997</td>\n",
       "      <td>95.00400</td>\n",
       "      <td>1.527</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4.073684</td>\n",
       "      <td>17.280700</td>\n",
       "      <td>14.100204</td>\n",
       "      <td>3.130435</td>\n",
       "      <td>0.20001</td>\n",
       "      <td>2.292929</td>\n",
       "      <td>0.04299</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>77</th>\n",
       "      <td>MO</td>\n",
       "      <td>Altria Group, Inc.</td>\n",
       "      <td>58.910000</td>\n",
       "      <td>56.66462</td>\n",
       "      <td>0.606</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4.957895</td>\n",
       "      <td>9.007646</td>\n",
       "      <td>11.011215</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>4.878788</td>\n",
       "      <td>0.20511</td>\n",
       "      <td>3.436782</td>\n",
       "      <td>4.08</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>91</th>\n",
       "      <td>VRTX</td>\n",
       "      <td>Vertex Pharmaceuticals Incorpor</td>\n",
       "      <td>504.769989</td>\n",
       "      <td>496.77585</td>\n",
       "      <td>0.415</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>26.892380</td>\n",
       "      <td>1.043478</td>\n",
       "      <td>-0.03152</td>\n",
       "      <td>4.191919</td>\n",
       "      <td>0.12683</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "    </tr>\n",
       "    <tr>\n",
       "      <th>97</th>\n",
       "      <td>TFC</td>\n",
       "      <td>Truist Financial Corporation</td>\n",
       "      <td>40.549999</td>\n",
       "      <td>51.66050</td>\n",
       "      <td>1.059</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>NaN</td>\n",
       "      <td>10.265822</td>\n",
       "      <td>1.086957</td>\n",
       "      <td>-0.00073</td>\n",
       "      <td>1.080808</td>\n",
       "      <td>-0.00008</td>\n",
       "      <td>2.149425</td>\n",
       "      <td>2.08</td>\n",
       "    </tr>\n",
       "  </tbody>\n",
       "</table>\n",
       "<p>100 rows × 15 columns</p>\n",
       "</div>"
      ],
      "text/plain": [
       "   Ticker                     Company Name        Price     YTarget   Beta  \\\n",
       "49    CAT                Caterpillar, Inc.   339.640015   391.12564  1.138   \n",
       "17     HD           Home Depot, Inc. (The)   351.309998   431.95514  1.090   \n",
       "58    LMT      Lockheed Martin Corporation   466.170013   544.62410  0.427   \n",
       "22    MRK            Merck & Company, Inc.    94.570000   112.28545  0.363   \n",
       "43   QCOM            QUALCOMM Incorporated   156.580002   198.49700  1.289   \n",
       "..    ...                              ...          ...         ...    ...   \n",
       "62   BKNG  Booking Holdings Inc. Common St  4465.479980  5636.97600  1.404   \n",
       "73   PYPL            PayPal Holdings, Inc.    68.949997    95.00400  1.527   \n",
       "77     MO               Altria Group, Inc.    58.910000    56.66462  0.606   \n",
       "91   VRTX  Vertex Pharmaceuticals Incorpor   504.769989   496.77585  0.415   \n",
       "97    TFC     Truist Financial Corporation    40.549999    51.66050  1.059   \n",
       "\n",
       "       Score  PE_Score  PE Ratio TTM  PE Forward  ROE_Score      ROE  \\\n",
       "49  4.291451  4.326316     15.410163   15.333635   4.565217  0.55327   \n",
       "17  4.286908  3.273684     23.577852   22.519870   5.000000  3.85372   \n",
       "58  4.174352  3.610526     20.876400   16.583778   4.695652  0.81045   \n",
       "22  4.114825  4.452632     14.031158   10.060638   4.260870  0.40789   \n",
       "43  4.009431  4.115789     16.891047   12.802944   4.304348  0.41968   \n",
       "..       ...       ...           ...         ...        ...      ...   \n",
       "62       NaN  3.021053     25.840403   21.279388        NaN      NaN   \n",
       "73       NaN  4.073684     17.280700   14.100204   3.130435  0.20001   \n",
       "77       NaN  4.957895      9.007646   11.011215        NaN      NaN   \n",
       "91       NaN       NaN           NaN   26.892380   1.043478 -0.03152   \n",
       "97       NaN       NaN           NaN   10.265822   1.086957 -0.00073   \n",
       "\n",
       "    ROA_Score      ROA  Dividend_Score  Dividend Paid  \n",
       "49   3.828283  0.09675        4.034483           5.64  \n",
       "17   4.595960  0.15585        4.678161           9.20  \n",
       "58   3.585859  0.08306        4.862069          13.20  \n",
       "22   4.353535  0.13903        2.747126           3.24  \n",
       "43   4.151515  0.12626        2.931034           3.40  \n",
       "..        ...      ...             ...            ...  \n",
       "62   4.838384  0.18225        5.000000          38.40  \n",
       "73   2.292929  0.04299             NaN            NaN  \n",
       "77   4.878788  0.20511        3.436782           4.08  \n",
       "91   4.191919  0.12683             NaN            NaN  \n",
       "97   1.080808 -0.00008        2.149425           2.08  \n",
       "\n",
       "[100 rows x 15 columns]"
      ]
     },
     "execution_count": 6,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "df"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "9d412207-78ef-407b-bb3d-a0661aa72a4e",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
